### ISSUE TITLE
Discussion: Version 1.0 - milestones and strategies

### ISSUE THREAD

**Issue by FabianHofmann** [PyPSA/PyPSA#290]
I want to open a discussion about pypsa's roadmap towards its first major version 1.0, gather ideas and wishes on how the package should look like and what it should do. To start, here are some of my suggestions  

# API Revision
* [ ] Add docstrings to all functions, classes and modules
* [ ] Establish a harmonized naming convention (eg `n` for networks, `c` for component, `sn` for snapshot)
* [ ]  Increase test coverage > 90% (#231, #234)
* [ ] Move to the black coding style with commit hash in `.git-blame-ignore-revs` 
* [ ] Integrate pre-commit hooks for code spell checking and possible other checks
* [ ] ...

# API Extension
* [ ] Integrate `linopy` as new solver interface
* [ ] Possibly drop support for `pyomo`, remove the modules
* [ ] Add a `clustering` module with submodule `spatial` and `temporal` with according functions
* [ ] ...

# API Vision (for dreamers)
* [ ] Components are not pure dataframes but python classes which represent containers. For example, `n.generators` is a `GeneratorContainer` class or `Generators` class (an subclass of the `ComponentContainer` or `Components`) with various attributes like `static` for the static dataframe, `dynamic` for the timedependant dataframes, or even shortcuts, like `n.generators.p` which would directly return the time-dependent dispatch.  These containers could have component specific front-end functions like `add_ocgt` which has all the technological data for OCGT power plants.  
* [ ] ...

There is plenty of stuff we could add. Please feel free to extent edit the list. It might also be worthwhile to open a GH project for this.
