### ISSUE TITLE
Use ruff

### ISSUE THREAD

**Issue by lkstrp** [PyPSA/PyPSA#899]
[Ruff](https://docs.astral.sh/ruff/) is a very fast linter and formatter. It combines some of the tools we use right now and offers many more. We could simplify the existing linting and give all developers more direct feedback/ enforce more lint rules when using it, via `pre-commit` + uniform and better IDE/ CLI feedback.

Advantages:
- Better CLI/ IDE integration than `pre-commit`. Like `black` but with linting.
- Allows for dev feedback on things which the linter can't solve (like bare excepts, docstrings etc.)
- Many more rules could be added
- Fast
- Fewer dependencies to track

We could add it in multiple steps:
- [x] (1) Apply Basic Ruff settings (done in #900)
- [x] (2) Move existing linters to ruff (we can just keep the the stuff Ruff can't do) (done in #901)
- [x] (3) Let pre commit fail when manual fixes are needed (done in #901)
- [ ] (4) Add more rules
- [ ] Add to developer contribution documentation

Nothing of this is urgent. I just added a PR for the first step, so people can play around and are not buried in warnings.

### Tools:
In use right now (`pre-commit`).

Formatter:
- black
    - Ruff equivalent: yes

Linter:
- isort
    - Ruff equivalent: yes
- absolufy-imports
    - Ruff equivalent: yes
- codespell
    - Ruff equivalent:  I don't think so
- docformatter
    - Ruff equivalent: similar rules exist
- jupyter remove output
    - Ruff equivalent:  I don't think so
- pretty yaml
    - Ruff equivalent:  I don't think so
- end of file fixer/ trailing whitespaces, mixed line ending etc.
    - Ruff equivalent:  I think so

Static type checker
- mypy (not in use yet but planned)
    - Ruff equivalent:  Not implemented yet but in dev

And tons of more stuff can be set up: [Rules - Ruff](https://docs.astral.sh/ruff/rules/)
